apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: arm-hello-world
  name: arm-hello-world
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arm-hello-world
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: arm-hello-world
    spec:
      containers:
        - image: dylanmunyard/arm-hello-world:1.1
          imagePullPolicy: Always
          name: arm-hello-world
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: arm-hello-world
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 17882
      protocol: TCP
      targetPort: 80
  selector:
    app: arm-hello-world