---
apiVersion: v1
kind: Namespace
metadata:
  name: arm-core
---
apiVersion: v1
kind: Secret
metadata:
  name: arm-core-db
  namespace: arm-core 
type: Opaque
stringData:
  CONNECTION_STRING: "server=my-sql.my-sql.svc.cluster.local;Port=18888;database=arm-core;user=root;password=" # fill in the password before applying
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: arm-hello-world
  name: arm-hello-world
  namespace: arm-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arm-hello-world
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: arm-hello-world
    spec:
      containers:
        - image: dylanmunyard/arm-hello-world:1.3
          imagePullPolicy: Always
          name: arm-hello-world
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: ConnectionStrings__ArmDb
              valueFrom:
                secretKeyRef:
                  name: arm-core-db
                  key: CONNECTION_STRING
          ports:
            - containerPort: 80
              protocol: TCP
      nodeSelector:
        kubernetes.io/os: linux
        pi_level: "level2"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: arm-hello-world
  namespace: arm-core
spec:
  type: LoadBalancer
  ports:
    - port: 17883
      protocol: TCP
      targetPort: 80
  selector:
    app: arm-hello-world